Default: &defaults
  user: personallibrary
  password: personallibrary
  host: localhost
  port: 5432
  database: personallibrary
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: personallibrary_test
  <<: *defaults

Staging:
  database: personallibrary_staging
  poolsize: 100
  <<: *defaults

Production:
  database: personallibrary_production
  poolsize: 100
  <<: *defaults
